name: flutter-folio
version: 0.1.0
summary: Record and share travel experiences
description: A rich cross platform app for creating and sharing immersive travel memoirs

confinement: strict
base: core18
grade: stable

apps:
  flutter-folio:
    command: flutter_folio
    extensions: [flutter-master]
    plugs:
    - network

parts:
  flutter-folio:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart

